//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Reminder')
export class ReminderEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  ReminderType: string;

  @Column('date', { nullable: true })
  ReminderTime: Date;

  @Column('text', { nullable: true })
  DescriptionOrQuantity: string;
}
