//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import {
  WeeklyAndDailyPlannerList,
  WeeklyAndDailyPlannerCreate,
  WeeklyAndDailyPlannerEdit,
} from './resources/WeeklyAndDailyPlanner';
import { NotesList, NotesCreate, NotesEdit } from './resources/Notes';
import {
  ReminderList,
  ReminderCreate,
  ReminderEdit,
} from './resources/Reminder';
import {
  ToDoListList,
  ToDoListCreate,
  ToDoListEdit,
} from './resources/ToDoList';
import {
  ScheduleList,
  ScheduleCreate,
  ScheduleEdit,
} from './resources/Schedule';
import WeeklyAndDailyPlannerIcon from '@mui/icons-material/EventNote';
import NotesIcon from '@mui/icons-material/Note';
import ReminderIcon from '@mui/icons-material/Notifications';
import ToDoListIcon from '@mui/icons-material/FormatListBulleted';
import ScheduleIcon from '@mui/icons-material/Schedule';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/a1aee024b">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="WeeklyAndDailyPlanner"
          options={{ label: 'Weekly And Daily Planner' }}
          list={WeeklyAndDailyPlannerList}
          create={WeeklyAndDailyPlannerCreate}
          edit={WeeklyAndDailyPlannerEdit}
          recordRepresentation="Days"
          icon={WeeklyAndDailyPlannerIcon}
        />
        <Resource
          name="Notes"
          options={{ label: 'Notes' }}
          list={NotesList}
          create={NotesCreate}
          edit={NotesEdit}
          recordRepresentation="Content"
          icon={NotesIcon}
        />
        <Resource
          name="Reminder"
          options={{ label: 'Reminder' }}
          list={ReminderList}
          create={ReminderCreate}
          edit={ReminderEdit}
          recordRepresentation="ReminderType"
          icon={ReminderIcon}
        />
        <Resource
          name="ToDoList"
          options={{ label: 'To Do List' }}
          list={ToDoListList}
          create={ToDoListCreate}
          edit={ToDoListEdit}
          recordRepresentation="Task"
          icon={ToDoListIcon}
        />
        <Resource
          name="Schedule"
          options={{ label: 'Schedule' }}
          list={ScheduleList}
          create={ScheduleCreate}
          edit={ScheduleEdit}
          recordRepresentation="id"
          icon={ScheduleIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
