//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    WeeklyAndDailyPlanner: {
      name: 'Weekly And Daily Planner',
      fields: { Days: 'Days', id: 'id' },
    },
    Notes: { name: 'Notes', fields: { Content: 'Content', id: 'id' } },
    Reminder: {
      name: 'Reminder',
      fields: {
        ReminderType: 'Reminder Type',
        ReminderTime: 'Reminder Time',
        DescriptionOrQuantity: 'Description Or Quantity',
        id: 'id',
      },
    },
    ToDoList: { name: 'To Do List', fields: { Task: 'Task', id: 'id' } },
    Schedule: {
      name: 'Schedule',
      fields: {
        Date: 'Date',
        StartTime: 'Start Time',
        EndTime: 'End Time',
        Description: 'Description',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    WeeklyAndDailyPlanner: {
      name: 'Weekly And Daily Planner (fr)',
      fields: { Days: 'Days (fr)', id: 'id' },
    },
    Notes: {
      name: 'Notes (fr)',
      fields: { Content: 'Content (fr)', id: 'id' },
    },
    Reminder: {
      name: 'Reminder (fr)',
      fields: {
        ReminderType: 'Reminder Type (fr)',
        ReminderTime: 'Reminder Time (fr)',
        DescriptionOrQuantity: 'Description Or Quantity (fr)',
        id: 'id',
      },
    },
    ToDoList: {
      name: 'To Do List (fr)',
      fields: { Task: 'Task (fr)', id: 'id' },
    },
    Schedule: {
      name: 'Schedule (fr)',
      fields: {
        Date: 'Date (fr)',
        StartTime: 'Start Time (fr)',
        EndTime: 'End Time (fr)',
        Description: 'Description (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
